collaborators:
  Mariocj89:
    permission: admin
hooks:
  travis:
    active: true
    config:
      domain: notify.travis-ci.org
      token: '********'
      user: Mariocj89
    events:
    - create
    - delete
    - issue_comment
    - member
    - membership
    - public
    - pull_request
    - push
    - repository
labels:
  bug:
    color: ee0701
  enhancement:
    color: 84b6eb
  help wanted:
    color: 128A0C
  question:
    color: cc317c
  web:
    color: 5319e7
  wontfix:
    color: ffffff
options:
  description: Stop managing your github config like a mere human
  has_downloads: true
  has_issues: true
  has_wiki: true
  homepage: null
  name: dothub
  private: false
