collaborators:
  mariocj89:
    permission: admin
hooks:
- active: true
  config:
    domain: notify.travis-ci.org
    token: '********'
    user: Mariocj89
  events:
  - create
  - delete
  - issue_comment
  - member
  - membership
  - public
  - pull_request
  - push
  - repository
  name: travis
- active: true
  config:
    content_type: json
    insecure_ssl: '0'
    secret: '********'
    url: https://kolkrabbi.heroku.com/hooks/github
  events:
  - '*'
  name: web
- active: true
  config: {}
  events:
  - pull_request
  - pull_request_review_comment
  - push
  - status
  name: landscape
labels:
  Hacktoberfest:
    color: 5319e7
  bug:
    color: ee0701
  enhancement:
    color: 84b6eb
  help wanted:
    color: 128A0C
  question:
    color: cc317c
  wontfix:
    color: ffffff
options:
  allow_merge_commit: true
  allow_rebase_merge: true
  allow_squash_merge: true
  description: Stop managing your github config like a mere human
  has_downloads: true
  has_issues: true
  has_wiki: true
  homepage: null
  name: dothub
  private: false
