sudo: false
language: python
python:
    - "2.7"
    - "3.4"
install: pip install tox-travis
script:
    - tox
    - if [ "${TRAVIS_BRANCH}" == "master" ]; then
        pip install dothub ;
        yes | dothub repo --owner=mariocj89 --repository=dothub push ;
      fi
